### ISSUE TITLE
Замечания по game.cpp

### ISSUE THREAD

**Issue by sergey-shambir** [JokerSSmile/MainGame#2]
- в функции Game::DrawPlayersHealth каждый раз пересоздаётся спрайт и перегружается текстура из файла, надо делать это один раз при инициализации.
- в функциях DrawEnemies, DrawBombs, IsLevelCleared, IsRoomEmpty, IsChestInRoom, CheckEnemyCollidesPlayer, SetCorrectDrawOrder надо вместо итераторов использовать range-based for. Можно также рассмотреть вариант использовать std::any_of и связку std::remove_if + метод erase у std::vector
- в методе IsIntersectsPlayerEnemy лишние else, зачем писать

``` cpp
if (A) {
  return true;
} else if (B) {
  return true;
} else {
  return false;
}
```

если всё равно после return функция дальше выполняться не будет и else попросту бесполезно?
- у функции UpdateBullets слишком большая вложенность

**Comment by JokerSSmile** [comment]
@sergey-shambir исправил

**Comment by sergey-shambir** [comment]
- что делает float gameTime = 0; в `void Game::InitGame()`?
- что за число возвращает InitializeLevel?
- в Game::DeleteEnemyFromVector() надо условие переписать

``` cpp
return !(enemy.health > 0);
return enemy.health < 0;
```

Я ведь правильно, понимаю, что enemy.health, как и положено, имеет тип unsigned?
- в Game::DrawEnemies проверка `if (enemy.life == true)` в общем-то избыточна, достаточно `if (enemy.life)`. Кстати, почему life, а не alive?
- в `bool Game::IsLevelCleared()` можно сократить проверку с помощью `&&`:

``` cpp
if (enemy.enemyLevel == level)
{
    if (enemy.health > 0)
    {
        isAllDead = false;
    }
}
/////////////////
if (enemy.enemyLevel == level && enemy.health > 0)
    [...]
```
- в `Game::IsChestInRoom()` проверка на размер массива излишняя

**Comment by JokerSSmile** [comment]
@sergey-shambir 
- enemy.health float, т. к. урон не является целочисленным
-  if (enemy.life == true) вроде бы вы говорили что можно писать и так, если соблюдать это во всем коде

Остальное исправлено
